# Generated by Django 6.0 on 2026-04-04 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookmarks", "0054_bookmarkbundle_filter_shared_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StartPage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "domain_grouping",
                    models.CharField(
                        choices=[
                            ("off", "Off"),
                            ("domain", "Domain"),
                            ("subdomain", "Subdomain"),
                        ],
                        default="off",
                        max_length=10,
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="StartPageWidget",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "widget_type",
                    models.CharField(
                        choices=[
                            ("bundle", "Bundle"),
                            ("tag", "Tag"),
                            ("filter", "Custom filter"),
                        ],
                        max_length=10,
                    ),
                ),
                ("tag_name", models.CharField(blank=True, max_length=64)),
                ("filter_query", models.CharField(blank=True, max_length=256)),
                (
                    "filter_unread",
                    models.CharField(
                        choices=[("off", "All"), ("yes", "Unread"), ("no", "Read")],
                        default="off",
                        max_length=3,
                    ),
                ),
                (
                    "filter_shared",
                    models.CharField(
                        choices=[("off", "All"), ("yes", "Shared"), ("no", "Unshared")],
                        default="off",
                        max_length=3,
                    ),
                ),
                (
                    "sort",
                    models.CharField(
                        choices=[
                            ("added_desc", "Added (newest)"),
                            ("added_asc", "Added (oldest)"),
                            ("title_asc", "Title (A-Z)"),
                            ("title_desc", "Title (Z-A)"),
                        ],
                        default="added_desc",
                        max_length=10,
                    ),
                ),
                ("max_items", models.IntegerField(default=20)),
                ("order", models.IntegerField(default=0)),
                (
                    "bundle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="bookmarks.bookmarkbundle",
                    ),
                ),
                (
                    "start_page",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="widgets",
                        to="startpage.startpage",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
