# Generated by Django 6.0 on 2026-04-19 07:37

from django.db import migrations, models


def copy_grouping_to_widgets(apps, schema_editor):
    StartPageWidget = apps.get_model("startpage", "StartPageWidget")
    for widget in StartPageWidget.objects.all().select_related("start_page"):
        widget.domain_grouping = widget.start_page.domain_grouping
        widget.save(update_fields=["domain_grouping"])


def copy_grouping_back_to_page(apps, schema_editor):
    StartPage = apps.get_model("startpage", "StartPage")
    StartPageWidget = apps.get_model("startpage", "StartPageWidget")
    for page in StartPage.objects.all():
        first = StartPageWidget.objects.filter(start_page=page).first()
        page.domain_grouping = first.domain_grouping if first else "off"
        page.save(update_fields=["domain_grouping"])


class Migration(migrations.Migration):
    dependencies = [
        ("startpage", "0002_smart_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="startpagewidget",
            name="domain_grouping",
            field=models.CharField(
                choices=[
                    ("off", "Off"),
                    ("domain", "Domain"),
                    ("subdomain", "Subdomain"),
                ],
                default="off",
                max_length=10,
            ),
        ),
        migrations.RunPython(
            copy_grouping_to_widgets,
            reverse_code=copy_grouping_back_to_page,
        ),
        migrations.RemoveField(
            model_name="startpage",
            name="domain_grouping",
        ),
    ]
